ignore:
  - vulnerability: GHSA-6vfc-qv3f-vr6c
    package:
      name: markdown-it
  - vulnerability: GHSA-v88g-cgmw-v5xw
    package:
      name: ajv
  - vulnerability: GHSA-282f-qqgm-c34q
    package:
      name: jsonpointer
  - vulnerability: GHSA-p9pc-299p-vxgp
    package:
      name: yargs-parser
  - vulnerability: CVE-2025-9230
    package:
      name: libcrypto3
  - vulnerability: CVE-2025-9230
    package:
      name: libssl3
  - vulnerability: CVE-2025-9232
    package:
      name: libcrypto3
  - vulnerability: CVE-2025-9232
    package:
      name: libssl3
  - vulnerability: CVE-2025-9231
    package:
      name: libcrypto3
  - vulnerability: CVE-2025-9231
    package:
      name: libssl3

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
